### ISSUE TITLE
The countryName field needed to be supplied and was missing

### ISSUE THREAD

**Issue by rock1103** [ria-ee/X-Road#28] opened 2017-04-14 03:22 UTC
now I sign the csr file with test-ca:
root@xroad-lxd-cp:/home/ca/CA# sign sign_csr_20170414_member_testcenterserver_MEMCLASSTEST_member1.der
Using configuration from CA.cnf
Check that the request matches the signature
Signature ok
The countryName field needed to be supplied and was missing
how to configure countryName?

thank you.

**Comment by rock1103** [comment] 2017-04-17 05:13
![1](https://cloud.githubusercontent.com/assets/7257681/25079499/9cc37482-236f-11e7-91ed-ae958d020d6c.jpg)

**Comment by iluwatar** [comment] 2017-04-19 06:52
Looks like the country name is missing from the test-CA DN parameters. Did you follow the instructions at https://github.com/ria-ee/X-Road/blob/develop/ansible/TESTCA.md?

**Comment by rock1103** [comment] 2017-04-19 08:13
yes,I have installed test-ca with ansible, and ansible does these steps automatically,and countryname is also configured.
![xroad1](https://cloud.githubusercontent.com/assets/7257681/25169561/1269661e-251a-11e7-9355-21d745534258.jpg)
and in the key and certificates page view of security server,I have generate the csr
![xroad2](https://cloud.githubusercontent.com/assets/7257681/25169571/1e36ad8a-251a-11e7-88c8-f48b6a727486.jpg)
then use these command,
root@xroad-lxd-cp:/home/ca/CA# sign sign_csr_20170414_member_testcenterserver_MEMCLASSTEST_member1.der
Using configuration from CA.cnf
Check that the request matches the signature
Signature ok
The countryName field needed to be supplied and was missing
also have this problem.

**Comment by iluwatar** [comment] 2017-04-19 08:34
Is this issue duplicate of https://github.com/ria-ee/X-Road/issues/31?

**Closed** 2017-04-20 02:33 UTC
